// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN8u9RevAPNQs2rqDSNmsfQFY4KNsXsy4',
    appId: '1:353804435927:web:cf79f00ec6bf5a47528b92',
    messagingSenderId: '353804435927',
    projectId: 'eduklio',
    authDomain: 'eduklio.firebaseapp.com',
    storageBucket: 'eduklio.appspot.com',
    measurementId: 'G-615EBTP0PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBhJ3FK3KNZA8Xqk-iAcArOJDev160YPI',
    appId: '1:353804435927:android:ad69158907e45553528b92',
    messagingSenderId: '353804435927',
    projectId: 'eduklio',
    storageBucket: 'eduklio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyM5ovaIndNYLSYvPW8eAGIpLj0b0oeZ4',
    appId: '1:353804435927:ios:9abe95ac199a1ada528b92',
    messagingSenderId: '353804435927',
    projectId: 'eduklio',
    storageBucket: 'eduklio.appspot.com',
    iosClientId: '353804435927-7cejp3n484o8ck9vsspbe22aa237nb36.apps.googleusercontent.com',
    iosBundleId: 'com.eduklio.app.eduklio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyM5ovaIndNYLSYvPW8eAGIpLj0b0oeZ4',
    appId: '1:353804435927:ios:9abe95ac199a1ada528b92',
    messagingSenderId: '353804435927',
    projectId: 'eduklio',
    storageBucket: 'eduklio.appspot.com',
    iosClientId: '353804435927-7cejp3n484o8ck9vsspbe22aa237nb36.apps.googleusercontent.com',
    iosBundleId: 'com.eduklio.app.eduklio',
  );
}
